# Generated by Django 4.2.11 on 2025-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='list_of_books',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='no_of_books',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
