# Generated by Django 4.2.11 on 2025-04-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_list_of_books_book_no_of_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='list_of_books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='no_of_books',
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('book_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_instances', to='bookstore.book')),
            ],
        ),
    ]
