# Generated by Django 4.2.11 on 2025-04-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_remove_book_list_of_books_remove_book_no_of_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_books', to='bookstore.book')),
            ],
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
