# Generated by Django 4.2.11 on 2025-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_subbook_delete_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_of_books',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
