# Generated by Django 4.2.11 on 2025-04-25 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_book_no_of_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbook',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
