# Generated by Django 4.2.11 on 2025-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_link', models.URLField()),
                ('filter_tag', models.CharField(choices=[('web-dev', 'Development'), ('web-des', 'Research'), ('dig-mar', 'Machine Learning')], max_length=20)),
            ],
        ),
    ]
