# Generated by Django 4.2.11 on 2025-05-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technology_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modal_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/modal/'),
        ),
    ]
