# Generated by Django 4.2.11 on 2025-05-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_content_recipe_procedure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='recipe',
        ),
    ]
