# Generated by Django 4.2.11 on 2025-05-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_procedure_recipe_steps_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(null=True, upload_to='recipes/covers'),
        ),
    ]
